import {
  UtensilsCrossed,
  Pizza,
  Beef,
  IceCream,
  Coffee,
  Sandwich,
  Soup,
  Salad,
  Cookie,
  Beer,
  Apple,
  Pill,
  Dog,
  ShoppingBag,
  Shirt,
  Footprints,
  Watch,
  Sparkles,
  Cat,
  Cake,
  Croissant,
  Wine,
  Fish,
  Carrot,
  Heart,
  Star,
  Gift,
  Truck,
  Store,
  Tag,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  UtensilsCrossed,
  Pizza,
  Beef,
  IceCream,
  Coffee,
  Sandwich,
  Soup,
  Salad,
  Cookie,
  Beer,
  Apple,
  Pill,
  Dog,
  ShoppingBag,
  Shirt,
  Footprints,
  Watch,
  Sparkles,
  Cat,
  Cake,
  Croissant,
  Wine,
  Fish,
  Carrot,
  Heart,
  Star,
  Gift,
  Truck,
  Store,
  Tag,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

export function getCategoryIcon(name: string | null | undefined): LucideIcon {
  if (name && CATEGORY_ICONS[name]) return CATEGORY_ICONS[name];
  return ShoppingBag;
}

// Paletas de cor pré-definidas (classes Tailwind) para o admin escolher.
export const CATEGORY_TINTS: Array<{ label: string; value: string }> = [
  { label: "Marca", value: "bg-brand-soft text-brand" },
  { label: "Verde", value: "bg-green-50 text-green-600" },
  { label: "Esmeralda", value: "bg-emerald-50 text-emerald-600" },
  { label: "Âmbar", value: "bg-amber-50 text-amber-600" },
  { label: "Âmbar escuro", value: "bg-amber-50 text-amber-700" },
  { label: "Laranja", value: "bg-orange-50 text-orange-600" },
  { label: "Amarelo", value: "bg-yellow-50 text-yellow-700" },
  { label: "Rosa", value: "bg-rose-50 text-rose-600" },
  { label: "Rosa escuro", value: "bg-rose-50 text-rose-700" },
  { label: "Pink", value: "bg-pink-50 text-pink-600" },
  { label: "Pink escuro", value: "bg-pink-50 text-pink-700" },
  { label: "Vermelho", value: "bg-red-50 text-red-600" },
  { label: "Roxo", value: "bg-purple-50 text-purple-600" },
  { label: "Fúcsia", value: "bg-fuchsia-50 text-fuchsia-600" },
  { label: "Índigo", value: "bg-indigo-50 text-indigo-600" },
  { label: "Azul céu", value: "bg-sky-50 text-sky-600" },
  { label: "Pedra", value: "bg-stone-100 text-stone-700" },
  { label: "Ardósia", value: "bg-slate-100 text-slate-700" },
];
