/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SacolaRouteImport } from './routes/sacola'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MeuTreinoRouteImport } from './routes/meu-treino'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CuponsRouteImport } from './routes/cupons'
import { Route as CompletarCadastroRouteImport } from './routes/completar-cadastro'
import { Route as ClubeRouteImport } from './routes/clube'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VitrineSlugRouteImport } from './routes/vitrine.$slug'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as PedidosLojaStoreIdRouteImport } from './routes/pedidos-loja.$storeId'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AdminStoriesRouteImport } from './routes/admin.stories'
import { Route as AdminServicosRouteImport } from './routes/admin.servicos'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPizzasRouteImport } from './routes/admin.pizzas'
import { Route as AdminModalBoasVindasRouteImport } from './routes/admin.modal-boas-vindas'
import { Route as AdminImpressaoAutomaticaRouteImport } from './routes/admin.impressao-automatica'
import { Route as AdminImportarCardapioRouteImport } from './routes/admin.importar-cardapio'
import { Route as AdminEntregasRouteImport } from './routes/admin.entregas'
import { Route as AdminDonosRouteImport } from './routes/admin.donos'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminCategoriasHomeRouteImport } from './routes/admin.categorias-home'
import { Route as AdminCategoriasEcommerceRouteImport } from './routes/admin.categorias-ecommerce'
import { Route as AdminAgendamentosRouteImport } from './routes/admin.agendamentos'
import { Route as PedidosLojaStoreIdImpressaoRouteImport } from './routes/pedidos-loja_.$storeId.impressao'
import { Route as AdminLojaStoreIdRouteImport } from './routes/admin.loja.$storeId'
import { Route as AdminEntregasRelatorioRouteImport } from './routes/admin.entregas.relatorio'
import { Route as AdminEntregasCadastroRouteImport } from './routes/admin.entregas.cadastro'
import { Route as AdminEntregasAreasRouteImport } from './routes/admin.entregas.areas'
import { Route as AdminAcademiaStoreIdRouteImport } from './routes/admin.academia.$storeId'
import { Route as PedidosLojaStoreIdEntregasRelatorioRouteImport } from './routes/pedidos-loja_.$storeId.entregas.relatorio'
import { Route as PedidosLojaStoreIdEntregasCadastroRouteImport } from './routes/pedidos-loja_.$storeId.entregas.cadastro'
import { Route as PedidosLojaStoreIdEntregasAreasRouteImport } from './routes/pedidos-loja_.$storeId.entregas.areas'

const SacolaRoute = SacolaRouteImport.update({
  id: '/sacola',
  path: '/sacola',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuTreinoRoute = MeuTreinoRouteImport.update({
  id: '/meu-treino',
  path: '/meu-treino',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponsRoute = CuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarCadastroRoute = CompletarCadastroRouteImport.update({
  id: '/completar-cadastro',
  path: '/completar-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeRoute = ClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VitrineSlugRoute = VitrineSlugRouteImport.update({
  id: '/vitrine/$slug',
  path: '/vitrine/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosLojaStoreIdRoute = PedidosLojaStoreIdRouteImport.update({
  id: '/pedidos-loja/$storeId',
  path: '/pedidos-loja/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoriesRoute = AdminStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPizzasRoute = AdminPizzasRouteImport.update({
  id: '/pizzas',
  path: '/pizzas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModalBoasVindasRoute = AdminModalBoasVindasRouteImport.update({
  id: '/modal-boas-vindas',
  path: '/modal-boas-vindas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpressaoAutomaticaRoute =
  AdminImpressaoAutomaticaRouteImport.update({
    id: '/impressao-automatica',
    path: '/impressao-automatica',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminImportarCardapioRoute = AdminImportarCardapioRouteImport.update({
  id: '/importar-cardapio',
  path: '/importar-cardapio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregasRoute = AdminEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonosRoute = AdminDonosRouteImport.update({
  id: '/donos',
  path: '/donos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasHomeRoute = AdminCategoriasHomeRouteImport.update({
  id: '/categorias-home',
  path: '/categorias-home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasEcommerceRoute =
  AdminCategoriasEcommerceRouteImport.update({
    id: '/categorias-ecommerce',
    path: '/categorias-ecommerce',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAgendamentosRoute = AdminAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AdminRoute,
} as any)
const PedidosLojaStoreIdImpressaoRoute =
  PedidosLojaStoreIdImpressaoRouteImport.update({
    id: '/pedidos-loja_/$storeId/impressao',
    path: '/pedidos-loja/$storeId/impressao',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLojaStoreIdRoute = AdminLojaStoreIdRouteImport.update({
  id: '/loja/$storeId',
  path: '/loja/$storeId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregasRelatorioRoute = AdminEntregasRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AdminEntregasRoute,
} as any)
const AdminEntregasCadastroRoute = AdminEntregasCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AdminEntregasRoute,
} as any)
const AdminEntregasAreasRoute = AdminEntregasAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AdminEntregasRoute,
} as any)
const AdminAcademiaStoreIdRoute = AdminAcademiaStoreIdRouteImport.update({
  id: '/academia/$storeId',
  path: '/academia/$storeId',
  getParentRoute: () => AdminRoute,
} as any)
const PedidosLojaStoreIdEntregasRelatorioRoute =
  PedidosLojaStoreIdEntregasRelatorioRouteImport.update({
    id: '/pedidos-loja_/$storeId/entregas/relatorio',
    path: '/pedidos-loja/$storeId/entregas/relatorio',
    getParentRoute: () => rootRouteImport,
  } as any)
const PedidosLojaStoreIdEntregasCadastroRoute =
  PedidosLojaStoreIdEntregasCadastroRouteImport.update({
    id: '/pedidos-loja_/$storeId/entregas/cadastro',
    path: '/pedidos-loja/$storeId/entregas/cadastro',
    getParentRoute: () => rootRouteImport,
  } as any)
const PedidosLojaStoreIdEntregasAreasRoute =
  PedidosLojaStoreIdEntregasAreasRouteImport.update({
    id: '/pedidos-loja_/$storeId/entregas/areas',
    path: '/pedidos-loja/$storeId/entregas/areas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendamentos': typeof AgendamentosRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/clube': typeof ClubeRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/cupons': typeof CuponsRoute
  '/favoritos': typeof FavoritosRoute
  '/meu-treino': typeof MeuTreinoRoute
  '/painel': typeof PainelRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sacola': typeof SacolaRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/categorias-ecommerce': typeof AdminCategoriasEcommerceRoute
  '/admin/categorias-home': typeof AdminCategoriasHomeRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/donos': typeof AdminDonosRoute
  '/admin/entregas': typeof AdminEntregasRouteWithChildren
  '/admin/importar-cardapio': typeof AdminImportarCardapioRoute
  '/admin/impressao-automatica': typeof AdminImpressaoAutomaticaRoute
  '/admin/modal-boas-vindas': typeof AdminModalBoasVindasRoute
  '/admin/pizzas': typeof AdminPizzasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedidos-loja/$storeId': typeof PedidosLojaStoreIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vitrine/$slug': typeof VitrineSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/academia/$storeId': typeof AdminAcademiaStoreIdRoute
  '/admin/entregas/areas': typeof AdminEntregasAreasRoute
  '/admin/entregas/cadastro': typeof AdminEntregasCadastroRoute
  '/admin/entregas/relatorio': typeof AdminEntregasRelatorioRoute
  '/admin/loja/$storeId': typeof AdminLojaStoreIdRoute
  '/pedidos-loja/$storeId/impressao': typeof PedidosLojaStoreIdImpressaoRoute
  '/pedidos-loja/$storeId/entregas/areas': typeof PedidosLojaStoreIdEntregasAreasRoute
  '/pedidos-loja/$storeId/entregas/cadastro': typeof PedidosLojaStoreIdEntregasCadastroRoute
  '/pedidos-loja/$storeId/entregas/relatorio': typeof PedidosLojaStoreIdEntregasRelatorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/clube': typeof ClubeRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/cupons': typeof CuponsRoute
  '/favoritos': typeof FavoritosRoute
  '/meu-treino': typeof MeuTreinoRoute
  '/painel': typeof PainelRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sacola': typeof SacolaRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/categorias-ecommerce': typeof AdminCategoriasEcommerceRoute
  '/admin/categorias-home': typeof AdminCategoriasHomeRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/donos': typeof AdminDonosRoute
  '/admin/entregas': typeof AdminEntregasRouteWithChildren
  '/admin/importar-cardapio': typeof AdminImportarCardapioRoute
  '/admin/impressao-automatica': typeof AdminImpressaoAutomaticaRoute
  '/admin/modal-boas-vindas': typeof AdminModalBoasVindasRoute
  '/admin/pizzas': typeof AdminPizzasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedidos-loja/$storeId': typeof PedidosLojaStoreIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vitrine/$slug': typeof VitrineSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/academia/$storeId': typeof AdminAcademiaStoreIdRoute
  '/admin/entregas/areas': typeof AdminEntregasAreasRoute
  '/admin/entregas/cadastro': typeof AdminEntregasCadastroRoute
  '/admin/entregas/relatorio': typeof AdminEntregasRelatorioRoute
  '/admin/loja/$storeId': typeof AdminLojaStoreIdRoute
  '/pedidos-loja/$storeId/impressao': typeof PedidosLojaStoreIdImpressaoRoute
  '/pedidos-loja/$storeId/entregas/areas': typeof PedidosLojaStoreIdEntregasAreasRoute
  '/pedidos-loja/$storeId/entregas/cadastro': typeof PedidosLojaStoreIdEntregasCadastroRoute
  '/pedidos-loja/$storeId/entregas/relatorio': typeof PedidosLojaStoreIdEntregasRelatorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendamentos': typeof AgendamentosRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/clube': typeof ClubeRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/cupons': typeof CuponsRoute
  '/favoritos': typeof FavoritosRoute
  '/meu-treino': typeof MeuTreinoRoute
  '/painel': typeof PainelRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sacola': typeof SacolaRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/categorias-ecommerce': typeof AdminCategoriasEcommerceRoute
  '/admin/categorias-home': typeof AdminCategoriasHomeRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/donos': typeof AdminDonosRoute
  '/admin/entregas': typeof AdminEntregasRouteWithChildren
  '/admin/importar-cardapio': typeof AdminImportarCardapioRoute
  '/admin/impressao-automatica': typeof AdminImpressaoAutomaticaRoute
  '/admin/modal-boas-vindas': typeof AdminModalBoasVindasRoute
  '/admin/pizzas': typeof AdminPizzasRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedidos-loja/$storeId': typeof PedidosLojaStoreIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vitrine/$slug': typeof VitrineSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/academia/$storeId': typeof AdminAcademiaStoreIdRoute
  '/admin/entregas/areas': typeof AdminEntregasAreasRoute
  '/admin/entregas/cadastro': typeof AdminEntregasCadastroRoute
  '/admin/entregas/relatorio': typeof AdminEntregasRelatorioRoute
  '/admin/loja/$storeId': typeof AdminLojaStoreIdRoute
  '/pedidos-loja_/$storeId/impressao': typeof PedidosLojaStoreIdImpressaoRoute
  '/pedidos-loja_/$storeId/entregas/areas': typeof PedidosLojaStoreIdEntregasAreasRoute
  '/pedidos-loja_/$storeId/entregas/cadastro': typeof PedidosLojaStoreIdEntregasCadastroRoute
  '/pedidos-loja_/$storeId/entregas/relatorio': typeof PedidosLojaStoreIdEntregasRelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendamentos'
    | '/auth'
    | '/busca'
    | '/clube'
    | '/completar-cadastro'
    | '/cupons'
    | '/favoritos'
    | '/meu-treino'
    | '/painel'
    | '/pedidos'
    | '/perfil'
    | '/reset-password'
    | '/sacola'
    | '/admin/agendamentos'
    | '/admin/categorias-ecommerce'
    | '/admin/categorias-home'
    | '/admin/cupons'
    | '/admin/donos'
    | '/admin/entregas'
    | '/admin/importar-cardapio'
    | '/admin/impressao-automatica'
    | '/admin/modal-boas-vindas'
    | '/admin/pizzas'
    | '/admin/produtos'
    | '/admin/servicos'
    | '/admin/stories'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/pedidos-loja/$storeId'
    | '/produto/$id'
    | '/vitrine/$slug'
    | '/admin/'
    | '/admin/academia/$storeId'
    | '/admin/entregas/areas'
    | '/admin/entregas/cadastro'
    | '/admin/entregas/relatorio'
    | '/admin/loja/$storeId'
    | '/pedidos-loja/$storeId/impressao'
    | '/pedidos-loja/$storeId/entregas/areas'
    | '/pedidos-loja/$storeId/entregas/cadastro'
    | '/pedidos-loja/$storeId/entregas/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamentos'
    | '/auth'
    | '/busca'
    | '/clube'
    | '/completar-cadastro'
    | '/cupons'
    | '/favoritos'
    | '/meu-treino'
    | '/painel'
    | '/pedidos'
    | '/perfil'
    | '/reset-password'
    | '/sacola'
    | '/admin/agendamentos'
    | '/admin/categorias-ecommerce'
    | '/admin/categorias-home'
    | '/admin/cupons'
    | '/admin/donos'
    | '/admin/entregas'
    | '/admin/importar-cardapio'
    | '/admin/impressao-automatica'
    | '/admin/modal-boas-vindas'
    | '/admin/pizzas'
    | '/admin/produtos'
    | '/admin/servicos'
    | '/admin/stories'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/pedidos-loja/$storeId'
    | '/produto/$id'
    | '/vitrine/$slug'
    | '/admin'
    | '/admin/academia/$storeId'
    | '/admin/entregas/areas'
    | '/admin/entregas/cadastro'
    | '/admin/entregas/relatorio'
    | '/admin/loja/$storeId'
    | '/pedidos-loja/$storeId/impressao'
    | '/pedidos-loja/$storeId/entregas/areas'
    | '/pedidos-loja/$storeId/entregas/cadastro'
    | '/pedidos-loja/$storeId/entregas/relatorio'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendamentos'
    | '/auth'
    | '/busca'
    | '/clube'
    | '/completar-cadastro'
    | '/cupons'
    | '/favoritos'
    | '/meu-treino'
    | '/painel'
    | '/pedidos'
    | '/perfil'
    | '/reset-password'
    | '/sacola'
    | '/admin/agendamentos'
    | '/admin/categorias-ecommerce'
    | '/admin/categorias-home'
    | '/admin/cupons'
    | '/admin/donos'
    | '/admin/entregas'
    | '/admin/importar-cardapio'
    | '/admin/impressao-automatica'
    | '/admin/modal-boas-vindas'
    | '/admin/pizzas'
    | '/admin/produtos'
    | '/admin/servicos'
    | '/admin/stories'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/pedidos-loja/$storeId'
    | '/produto/$id'
    | '/vitrine/$slug'
    | '/admin/'
    | '/admin/academia/$storeId'
    | '/admin/entregas/areas'
    | '/admin/entregas/cadastro'
    | '/admin/entregas/relatorio'
    | '/admin/loja/$storeId'
    | '/pedidos-loja_/$storeId/impressao'
    | '/pedidos-loja_/$storeId/entregas/areas'
    | '/pedidos-loja_/$storeId/entregas/cadastro'
    | '/pedidos-loja_/$storeId/entregas/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendamentosRoute: typeof AgendamentosRoute
  AuthRoute: typeof AuthRoute
  BuscaRoute: typeof BuscaRoute
  ClubeRoute: typeof ClubeRoute
  CompletarCadastroRoute: typeof CompletarCadastroRoute
  CuponsRoute: typeof CuponsRoute
  FavoritosRoute: typeof FavoritosRoute
  MeuTreinoRoute: typeof MeuTreinoRoute
  PainelRoute: typeof PainelRoute
  PedidosRoute: typeof PedidosRoute
  PerfilRoute: typeof PerfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SacolaRoute: typeof SacolaRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  LojaSlugRoute: typeof LojaSlugRoute
  PedidosLojaStoreIdRoute: typeof PedidosLojaStoreIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  VitrineSlugRoute: typeof VitrineSlugRoute
  PedidosLojaStoreIdImpressaoRoute: typeof PedidosLojaStoreIdImpressaoRoute
  PedidosLojaStoreIdEntregasAreasRoute: typeof PedidosLojaStoreIdEntregasAreasRoute
  PedidosLojaStoreIdEntregasCadastroRoute: typeof PedidosLojaStoreIdEntregasCadastroRoute
  PedidosLojaStoreIdEntregasRelatorioRoute: typeof PedidosLojaStoreIdEntregasRelatorioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sacola': {
      id: '/sacola'
      path: '/sacola'
      fullPath: '/sacola'
      preLoaderRoute: typeof SacolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-treino': {
      id: '/meu-treino'
      path: '/meu-treino'
      fullPath: '/meu-treino'
      preLoaderRoute: typeof MeuTreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupons': {
      id: '/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof CuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-cadastro': {
      id: '/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/completar-cadastro'
      preLoaderRoute: typeof CompletarCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube': {
      id: '/clube'
      path: '/clube'
      fullPath: '/clube'
      preLoaderRoute: typeof ClubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vitrine/$slug': {
      id: '/vitrine/$slug'
      path: '/vitrine/$slug'
      fullPath: '/vitrine/$slug'
      preLoaderRoute: typeof VitrineSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos-loja/$storeId': {
      id: '/pedidos-loja/$storeId'
      path: '/pedidos-loja/$storeId'
      fullPath: '/pedidos-loja/$storeId'
      preLoaderRoute: typeof PedidosLojaStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AdminStoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pizzas': {
      id: '/admin/pizzas'
      path: '/pizzas'
      fullPath: '/admin/pizzas'
      preLoaderRoute: typeof AdminPizzasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modal-boas-vindas': {
      id: '/admin/modal-boas-vindas'
      path: '/modal-boas-vindas'
      fullPath: '/admin/modal-boas-vindas'
      preLoaderRoute: typeof AdminModalBoasVindasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impressao-automatica': {
      id: '/admin/impressao-automatica'
      path: '/impressao-automatica'
      fullPath: '/admin/impressao-automatica'
      preLoaderRoute: typeof AdminImpressaoAutomaticaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importar-cardapio': {
      id: '/admin/importar-cardapio'
      path: '/importar-cardapio'
      fullPath: '/admin/importar-cardapio'
      preLoaderRoute: typeof AdminImportarCardapioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregas': {
      id: '/admin/entregas'
      path: '/entregas'
      fullPath: '/admin/entregas'
      preLoaderRoute: typeof AdminEntregasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donos': {
      id: '/admin/donos'
      path: '/donos'
      fullPath: '/admin/donos'
      preLoaderRoute: typeof AdminDonosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias-home': {
      id: '/admin/categorias-home'
      path: '/categorias-home'
      fullPath: '/admin/categorias-home'
      preLoaderRoute: typeof AdminCategoriasHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias-ecommerce': {
      id: '/admin/categorias-ecommerce'
      path: '/categorias-ecommerce'
      fullPath: '/admin/categorias-ecommerce'
      preLoaderRoute: typeof AdminCategoriasEcommerceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agendamentos': {
      id: '/admin/agendamentos'
      path: '/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AdminAgendamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedidos-loja_/$storeId/impressao': {
      id: '/pedidos-loja_/$storeId/impressao'
      path: '/pedidos-loja/$storeId/impressao'
      fullPath: '/pedidos-loja/$storeId/impressao'
      preLoaderRoute: typeof PedidosLojaStoreIdImpressaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/loja/$storeId': {
      id: '/admin/loja/$storeId'
      path: '/loja/$storeId'
      fullPath: '/admin/loja/$storeId'
      preLoaderRoute: typeof AdminLojaStoreIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregas/relatorio': {
      id: '/admin/entregas/relatorio'
      path: '/relatorio'
      fullPath: '/admin/entregas/relatorio'
      preLoaderRoute: typeof AdminEntregasRelatorioRouteImport
      parentRoute: typeof AdminEntregasRoute
    }
    '/admin/entregas/cadastro': {
      id: '/admin/entregas/cadastro'
      path: '/cadastro'
      fullPath: '/admin/entregas/cadastro'
      preLoaderRoute: typeof AdminEntregasCadastroRouteImport
      parentRoute: typeof AdminEntregasRoute
    }
    '/admin/entregas/areas': {
      id: '/admin/entregas/areas'
      path: '/areas'
      fullPath: '/admin/entregas/areas'
      preLoaderRoute: typeof AdminEntregasAreasRouteImport
      parentRoute: typeof AdminEntregasRoute
    }
    '/admin/academia/$storeId': {
      id: '/admin/academia/$storeId'
      path: '/academia/$storeId'
      fullPath: '/admin/academia/$storeId'
      preLoaderRoute: typeof AdminAcademiaStoreIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedidos-loja_/$storeId/entregas/relatorio': {
      id: '/pedidos-loja_/$storeId/entregas/relatorio'
      path: '/pedidos-loja/$storeId/entregas/relatorio'
      fullPath: '/pedidos-loja/$storeId/entregas/relatorio'
      preLoaderRoute: typeof PedidosLojaStoreIdEntregasRelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos-loja_/$storeId/entregas/cadastro': {
      id: '/pedidos-loja_/$storeId/entregas/cadastro'
      path: '/pedidos-loja/$storeId/entregas/cadastro'
      fullPath: '/pedidos-loja/$storeId/entregas/cadastro'
      preLoaderRoute: typeof PedidosLojaStoreIdEntregasCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos-loja_/$storeId/entregas/areas': {
      id: '/pedidos-loja_/$storeId/entregas/areas'
      path: '/pedidos-loja/$storeId/entregas/areas'
      fullPath: '/pedidos-loja/$storeId/entregas/areas'
      preLoaderRoute: typeof PedidosLojaStoreIdEntregasAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminEntregasRouteChildren {
  AdminEntregasAreasRoute: typeof AdminEntregasAreasRoute
  AdminEntregasCadastroRoute: typeof AdminEntregasCadastroRoute
  AdminEntregasRelatorioRoute: typeof AdminEntregasRelatorioRoute
}

const AdminEntregasRouteChildren: AdminEntregasRouteChildren = {
  AdminEntregasAreasRoute: AdminEntregasAreasRoute,
  AdminEntregasCadastroRoute: AdminEntregasCadastroRoute,
  AdminEntregasRelatorioRoute: AdminEntregasRelatorioRoute,
}

const AdminEntregasRouteWithChildren = AdminEntregasRoute._addFileChildren(
  AdminEntregasRouteChildren,
)

interface AdminRouteChildren {
  AdminAgendamentosRoute: typeof AdminAgendamentosRoute
  AdminCategoriasEcommerceRoute: typeof AdminCategoriasEcommerceRoute
  AdminCategoriasHomeRoute: typeof AdminCategoriasHomeRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminDonosRoute: typeof AdminDonosRoute
  AdminEntregasRoute: typeof AdminEntregasRouteWithChildren
  AdminImportarCardapioRoute: typeof AdminImportarCardapioRoute
  AdminImpressaoAutomaticaRoute: typeof AdminImpressaoAutomaticaRoute
  AdminModalBoasVindasRoute: typeof AdminModalBoasVindasRoute
  AdminPizzasRoute: typeof AdminPizzasRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminStoriesRoute: typeof AdminStoriesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAcademiaStoreIdRoute: typeof AdminAcademiaStoreIdRoute
  AdminLojaStoreIdRoute: typeof AdminLojaStoreIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendamentosRoute: AdminAgendamentosRoute,
  AdminCategoriasEcommerceRoute: AdminCategoriasEcommerceRoute,
  AdminCategoriasHomeRoute: AdminCategoriasHomeRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminDonosRoute: AdminDonosRoute,
  AdminEntregasRoute: AdminEntregasRouteWithChildren,
  AdminImportarCardapioRoute: AdminImportarCardapioRoute,
  AdminImpressaoAutomaticaRoute: AdminImpressaoAutomaticaRoute,
  AdminModalBoasVindasRoute: AdminModalBoasVindasRoute,
  AdminPizzasRoute: AdminPizzasRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminStoriesRoute: AdminStoriesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAcademiaStoreIdRoute: AdminAcademiaStoreIdRoute,
  AdminLojaStoreIdRoute: AdminLojaStoreIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendamentosRoute: AgendamentosRoute,
  AuthRoute: AuthRoute,
  BuscaRoute: BuscaRoute,
  ClubeRoute: ClubeRoute,
  CompletarCadastroRoute: CompletarCadastroRoute,
  CuponsRoute: CuponsRoute,
  FavoritosRoute: FavoritosRoute,
  MeuTreinoRoute: MeuTreinoRoute,
  PainelRoute: PainelRoute,
  PedidosRoute: PedidosRoute,
  PerfilRoute: PerfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SacolaRoute: SacolaRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  LojaSlugRoute: LojaSlugRoute,
  PedidosLojaStoreIdRoute: PedidosLojaStoreIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  VitrineSlugRoute: VitrineSlugRoute,
  PedidosLojaStoreIdImpressaoRoute: PedidosLojaStoreIdImpressaoRoute,
  PedidosLojaStoreIdEntregasAreasRoute: PedidosLojaStoreIdEntregasAreasRoute,
  PedidosLojaStoreIdEntregasCadastroRoute:
    PedidosLojaStoreIdEntregasCadastroRoute,
  PedidosLojaStoreIdEntregasRelatorioRoute:
    PedidosLojaStoreIdEntregasRelatorioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
