/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SacolaRouteImport } from './routes/sacola'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CompletarCadastroRouteImport } from './routes/completar-cadastro'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VitrineSlugRouteImport } from './routes/vitrine.$slug'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'

const SacolaRoute = SacolaRouteImport.update({
  id: '/sacola',
  path: '/sacola',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarCadastroRoute = CompletarCadastroRouteImport.update({
  id: '/completar-cadastro',
  path: '/completar-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineSlugRoute = VitrineSlugRouteImport.update({
  id: '/vitrine/$slug',
  path: '/vitrine/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/favoritos': typeof FavoritosRoute
  '/perfil': typeof PerfilRoute
  '/sacola': typeof SacolaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vitrine/$slug': typeof VitrineSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/favoritos': typeof FavoritosRoute
  '/perfil': typeof PerfilRoute
  '/sacola': typeof SacolaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vitrine/$slug': typeof VitrineSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/favoritos': typeof FavoritosRoute
  '/perfil': typeof PerfilRoute
  '/sacola': typeof SacolaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/vitrine/$slug': typeof VitrineSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/completar-cadastro'
    | '/favoritos'
    | '/perfil'
    | '/sacola'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/produto/$id'
    | '/vitrine/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/completar-cadastro'
    | '/favoritos'
    | '/perfil'
    | '/sacola'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/produto/$id'
    | '/vitrine/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/busca'
    | '/completar-cadastro'
    | '/favoritos'
    | '/perfil'
    | '/sacola'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/produto/$id'
    | '/vitrine/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscaRoute: typeof BuscaRoute
  CompletarCadastroRoute: typeof CompletarCadastroRoute
  FavoritosRoute: typeof FavoritosRoute
  PerfilRoute: typeof PerfilRoute
  SacolaRoute: typeof SacolaRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  LojaSlugRoute: typeof LojaSlugRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  VitrineSlugRoute: typeof VitrineSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sacola': {
      id: '/sacola'
      path: '/sacola'
      fullPath: '/sacola'
      preLoaderRoute: typeof SacolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-cadastro': {
      id: '/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/completar-cadastro'
      preLoaderRoute: typeof CompletarCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine/$slug': {
      id: '/vitrine/$slug'
      path: '/vitrine/$slug'
      fullPath: '/vitrine/$slug'
      preLoaderRoute: typeof VitrineSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscaRoute: BuscaRoute,
  CompletarCadastroRoute: CompletarCadastroRoute,
  FavoritosRoute: FavoritosRoute,
  PerfilRoute: PerfilRoute,
  SacolaRoute: SacolaRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  LojaSlugRoute: LojaSlugRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  VitrineSlugRoute: VitrineSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
